# @package _global_

defaults:
  - _self_
  - data: cpgcorpus # choose datamodule with `test_dataloader()` for evaluation
  - model: default
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

val: true
test: true

# passing checkpoint and config paths is necessary for evaluation
model_ckpt_path: ???
config_path: ???

# Ensure strict loading of model weights
strict_load: true
