# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "val/loss_best"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: null

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: minimize

    # total number of runs that will be executed
    n_trials: 100

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
      n_startup_trials: 10 # number of random sampling runs before optimization starts

    # define hyperparameter search space
    params:
      model.optimizer.lr: interval(0.0001, 0.01)
      data.batch_size: choice(4, 8, 16)
      data.sorting_strategy: choice("sorted_chromosome", "random")
      model.scheduler.num_cycles: choice(0.5, 1.5, 2.5)
      model.net.n_layers: choice(4, 8, 16)
      model.net.d_hidden: choice(32, 64, 128)
      model.net.d_embedding: choice(32, 64, 128)
      model.net.activation: choice("relu", "swiglu", "gelu")
      model.net.positional_encoding: choice("none", "positional", "rotary")
      model.net.n_attention_heads: choice(4, 8)
      model.net.use_power_norm: choice(true, false)
      model.net.n_mlp_blocks: choice(1, 2, 3)
